added tutorial (init-tutorial.md) and its relevant image files
sierpinskiii/quisp-textbook.github.io pull request #4
Opened 2023-02-22 08:56 UTC by syuii

Not sure yet if the images work in the md file and may still need changes for more detailed parameter descriptions.

2023-02-23 02:22 UTC, Tatzhiro requested changes

2023-02-23 02:22 UTC, Tatzhiro commented on _toc.yml
> -- file: vscode
You shouldn't be deleting other files

2023-02-23 02:24 UTC, Tatzhiro requested changes
You should create an image folder or something and store all the png files there to keep the repository organized.
Change the path to the image file in your init-tutorial.md afterwards.

2023-03-07 04:41 UTC, sierpinskiii commented
Restored the deleted file. Everything else is fine as I think of. Nice work!

2023-03-07 04:45 UTC, sierpinskiii commented
Gotta restructure our directories including the image dir...

2023-03-08 02:53 UTC, merged